SVOAScheduling/Models/Assignment.cs
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.AspNetCore.Identity;

namespace SVOAScheduling.Models
{
    public class Assignment
    {
        [Key]
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        public int Id { get; set; }
        [DisplayName("Official")]
        public string OfficialId { get; set; }
        public Profile Official { get; set; }
        public string Gym { get; set; }
        [DisplayName("Assignment")]
        public int AssignmentTypeId { get; set; }
        [DisplayName("Assignment")]
        public AssignmentType Type { get; set; }
        public int GameId { get; set; }
        public Game Game { get; set; }


        public Assignment()
        {
        }
    }
}

SVOAScheduling/Models/AssignmentType.cs
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace SVOAScheduling.Models
{
    public class AssignmentType
    {

        [Key]
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        public int Id { get; set; }
        public string Description { get; set; }
        public int SortOrder { get; set; }
        public int? SportId { get; set; }


        public AssignmentType()
        {
        }
    }
}

SVOAScheduling/Models/ViewModels/AssignmentViewModel.cs
using System;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;

namespace SVOAScheduling.Models.ViewModels
{
    public class AssignmentViewModel
    {
        public int AssignmentId { get; set; }
        public int AssignmentTypeId { get; set; }
        public string AssignmentText { get; set; }
        [DisplayName("Official")]
        public string OfficialId { get; set; }
        public string OfficialName { get; set; }
        public string Gym { get; set; }
        public int SortOrder { get; set; }

        public AssignmentViewModel()
        {
        }
    }
}

SVOAScheduling/Areas/Identity/Pages/Role/Delete.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.Security;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using SVOAScheduling.Data;
using Microsoft.AspNetCore.Authorization;

namespace SVOAScheduling.Areas.Identity.Pages.Role
{
    [Authorize(Roles = ("System Administrator"))]
    public class DeleteModel : PageModel
    {
        private readonly RoleManager<IdentityRole> _roleManager;
        private readonly UserManager<IdentityUser> _userManager;
        private readonly ApplicationDbContext _context;

        public DeleteModel(RoleManager<IdentityRole> roleManager, UserManager<IdentityUser> userManager, ApplicationDbContext context)
        {
            _roleManager = roleManager;
            _userManager = userManager;
            _context = context;
        }

        [BindProperty]
        public IdentityRole Input { get; set; }

        public async Task<IActionResult> OnGet( string id)
        {
            Input = await _roleManager.FindByIdAsync(id);
            return Page();
        }

        public async Task<IActionResult> OnPost()
        {
            if (!ModelState.IsValid)
            {
                return Page();
            }

            var refereeRole = await _roleManager.FindByNameAsync("Referee");
            var role = await _roleManager.FindByIdAsync(Input.Id);
            var userList = await _userManager.GetUsersInRoleAsync(role.Name);

            foreach (var user in userList)
            {
                var addRoleResult = await _userManager.AddToRoleAsync(user, refereeRole.Id);
                if (!addRoleResult.Succeeded)
                {
                    foreach (var error in addRoleResult.Errors)
                    {
                        ModelState.AddModelError(string.Empty, error.Description);
                    }
                    return Page();
                }
                var removeResult = await _userManager.RemoveFromRoleAsync(user, role.Id);
                if (!removeResult.Succeeded)
                {
                    foreach (var error in removeResult.Errors)
                    {
                        ModelState.AddModelError(string.Empty, error.Description);
                    }
                    return Page();
                }
            }

            var result = await _roleManager.DeleteAsync(role);

            if (result.Succeeded)
            {
                return RedirectToPage("./Index");
            }
            return Page();
        }
    }
}

SVOAScheduling/Controllers/GameController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Security.Claims;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using SVOAScheduling.Data;
using SVOAScheduling.Models;
using SVOAScheduling.Models.ViewModels;
using SVOAScheduling.Services;

namespace SVOAScheduling.Controllers
{
    [Authorize(Roles = "Referee, Assignor, Admin, Super Administrator")]
    public class GameController : Controller
    {
        private readonly ApplicationDbContext _context;

        public GameController(ApplicationDbContext context)
        {
            _context = context;

        }

        // GET: Game
        public IActionResult Index()
        {

            var userId = User.FindFirstValue(ClaimTypes.NameIdentifier);
            var leagueId = RefereeServices.GetRefereeLeagueId(userId, _context);
            var seasonId = SeasonServices.GetCurrentSeason(_context, leagueId);
            var games = GameServices.GetGamesBySeason(_context, seasonId);

            var gameCount = games.Count();
            if (gameCount > 0)
            {
                var schedule = new List<FullScheduleViewModel>();

                foreach (Game game in games)
                {
                    FullScheduleViewModel sch = new FullScheduleViewModel();

                    sch.Id = game.Id;
                    sch.Location = game.Location.Name;
                    sch.Date = game.Date;
                    sch.Division = game.Division.Name;
                    sch.HomeTeam = game.HomeTeam.Abbreviation;
                    sch.VisitingTeam = game.VisitingTeam.Abbreviation;
                    sch.Number = game.Number;
                    sch.R1 = (game.GameAssignments.Any(ga => ga.Type.Description == "R1")) ? game.GameAssignments.FirstOrDefault(ga => ga.Type.Description == "R1").Official.FullName : "";
                    sch.R2 = (game.GameAssignments.Any(ga => ga.Type.Description == "R2")) ? game.GameAssignments.FirstOrDefault(ga => ga.Type.Description == "R2").Official.FullName : "";
                   

                    schedule.Add(sch);
                }


                return View(schedule.AsEnumerable());
            }
            return View(new List<FullScheduleViewModel>().AsEnumerable());
        }

        // GET: Game/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var game = await _context.Games
                .Include(g => g.Division)
                .Include(g => g.Format)
                .Include(g => g.Location)
                .Include(g => g.Payment)
                .Include(g => g.Season)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (game == null)
            {
                return NotFound();
            }

            return View(game);
        }

        // GET: Game/Create
        [Authorize(Roles = ("Assignor, Administrator"))]
        public IActionResult Create()
        {
            var userId = User.FindFirstValue(ClaimTypes.NameIdentifier);
            var siteSettings = RefereeServices.GetSiteSettings(_context, userId);
            var date = DateTime.Now;

            Game game = new Game()
            {
                IsActive = true,
                SeasonId = siteSettings.SeasonId,
                Date = new DateTime(date.Year, date.Month, date.Day, 17, 0, 0)
            };

            var locations = LocationServices.GetLocations(_context, siteSettings.OrganziationId);
            ViewData["DivisionId"] = new SelectList(DivisionServices.GetDivisions(_context, siteSettings.LeagueId), "Id", "Name");
            ViewData["FormatId"] = new SelectList(_context.Format, "Id", "Description");
            ViewData["LocationId"] = new SelectList(locations, "Id", "Name");
            ViewData["PaymentId"] = new SelectList(PaymentServices.GetPayments(_context, siteSettings.LeagueId), "Id", "Price");
            ViewData["SeasonId"] = new SelectList(SeasonServices.GetSeasons(_context, siteSettings.LeagueId), "Id", "Name");
            ViewData["HomeId"] = new SelectList(locations, "Id", "Name");
            ViewData["VisitorsId"] = new SelectList(locations, "Id", "Name");

            return View(game);
        }

        // POST: Game/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [Authorize(Roles = ("Assignor, Administrator"))]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,LocationId,SeasonId,Date,PaymentId,IsActive,FormatId,DivisionId,HomeTeamId,VisitingTeamId,Number")] Game game)
        {
            if (ModelState.IsValid)
            {
                _context.Add(game);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            var userId = User.FindFirstValue(ClaimTypes.NameIdentifier);
            var siteSettings = RefereeServices.GetSiteSettings(_context, userId);
            var locations = LocationServices.GetLocations(_context, siteSettings.OrganziationId);

            ViewData["DivisionId"] = new SelectList(DivisionServices.GetDivisions(_context, siteSettings.LeagueId), "Id", "Name", game.DivisionId);
            ViewData["FormatId"] = new SelectList(_context.Format, "Id", "Description", game.FormatId);
            ViewData["LocationId"] = new SelectList(locations, "Id", "Name", game.LocationId);
            ViewData["PaymentId"] = new SelectList(PaymentServices.GetPayments(_context, siteSettings.LeagueId), "Id", "Price", game.PaymentId);
            ViewData["SeasonId"] = new SelectList(SeasonServices.GetSeasons(_context, siteSettings.LeagueId), "Id", "Name", game.SeasonId);
            ViewData["HomeId"] = new SelectList(locations, "Id", "Name", game.HomeTeamId);
            ViewData["VisitorsId"] = new SelectList(locations, "Id", "Name", game.VisitingTeamId);
            return View(game);
        }

        // GET: Game/Edit/5
        [Authorize(Roles = ("Assignor, Administrator"))]
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var game = await _context.Games.FindAsync(id);
            if (game == null)
            {
                return NotFound();
            }
            var userId = User.FindFirstValue(ClaimTypes.NameIdentifier);
            var siteSettings = RefereeServices.GetSiteSettings(_context, userId);
            var locations = LocationServices.GetLocations(_context, siteSettings.OrganziationId);

            ViewData["DivisionId"] = new SelectList(DivisionServices.GetDivisions(_context, siteSettings.LeagueId), "Id", "Name", game.DivisionId);
            ViewData["FormatId"] = new SelectList(_context.Format, "Id", "Description", game.FormatId);
            ViewData["LocationId"] = new SelectList(locations, "Id", "Name", game.LocationId);
            ViewData["PaymentId"] = new SelectList(PaymentServices.GetPayments(_context, siteSettings.LeagueId), "Id", "Price", game.PaymentId);
            ViewData["SeasonId"] = new SelectList(SeasonServices.GetSeasons(_context, siteSettings.LeagueId), "Id", "Name", game.SeasonId);
            ViewData["HomeId"] = new SelectList(locations, "Id", "Name", game.HomeTeamId);
            ViewData["VisitorsId"] = new SelectList(locations, "Id", "Name", game.VisitingTeamId);
            return View(game);
        }

        // POST: Game/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [Authorize(Roles = ("Assignor, Administrator"))]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,LocationId,SeasonId,Date,PaymentId,IsActive,FormatId,DivisionId,HomeTeamId,VisitingTeamId,Number")] Game game)
        {
            if (id != game.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(game);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!GameServices.GameExists(_context, game.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            var userId = User.FindFirstValue(ClaimTypes.NameIdentifier);
            var siteSettings = RefereeServices.GetSiteSettings(_context, userId);
            var locations = LocationServices.GetLocations(_context, siteSettings.OrganziationId);

            ViewData["DivisionId"] = new SelectList(DivisionServices.GetDivisions(_context, siteSettings.LeagueId), "Id", "Name", game.DivisionId);
            ViewData["FormatId"] = new SelectList(_context.Format, "Id", "Description", game.FormatId);
            ViewData["LocationId"] = new SelectList(locations, "Id", "Name", game.LocationId);
            ViewData["PaymentId"] = new SelectList(PaymentServices.GetPayments(_context, siteSettings.LeagueId), "Id", "Price", game.PaymentId);

SVOAScheduling/Views/Assignment/Delete.cshtml
@model SVOAScheduling.Models.ViewModels.GameViewModel

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete these assignments?</h3>
<div>
    <h4>Game</h4>
    <div class="row">
        <div>
           @Html.DisplayFor(model => model.Locaton)
        </div>
        <div>
            @Html.DisplayFor(model => model.HomeTeam) vs @Html.DisplayFor(model => model.VisitingTeam)
        </div>
        <div>
            @Html.DisplayFor(model => model.DateOnly)
        </div>
    </div>
    <hr />
    <form asp-action="Delete">
    <div class="row">
        <div class="col-4">
            <div>
                <input type="checkbox" class="form-group" asp-for="@Model.Checked" />

                @Html.DisplayFor(model => model.GameNumber) at @Html.DisplayFor(model => model.TimeOnly)
            </div>
                @foreach(var assignment in Model.Assignments.OrderBy(a => a.SortOrder))
            {
            <div>
                @Html.DisplayFor(item => assignment.AssignmentText): @Html.DisplayFor(item => assignment.OfficialName)
             </div>
           }
        </div>
        @for (int j = 0; j <= Model.AffiliatedGames.Count()-1; j++)
        {
            <div class="col-4">
                <div>
                    <input type="checkbox" class="form-group" asp-for="@Model.AffiliatedGames[j].Checked" />
                    <input type="hidden" asp-for="@Model.AffiliatedGames[j].GameId" />

                    @Html.DisplayFor(item => Model.AffiliatedGames[j].GameNumber) at @Html.DisplayFor(item => Model.AffiliatedGames[j].TimeOnly)
                </div>
            @foreach (var assignment in Model.AffiliatedGames[j].Assignments.OrderBy(a => a.SortOrder))
            {
                <div>
                    @Html.DisplayFor(item => assignment.AssignmentText): @Html.DisplayFor(item => assignment.OfficialName)
                </div>
            }
            </div>
        }
    </div>
     <div class="row pt-5">
       <div class="col-6">
        <input type="hidden" asp-for="@Model.GameId" />
        <input type="submit" value="Delete" class="btn btn-danger" />
        </div>
        <div class="col-6 text-end">
        <a asp-action="Modify" asp-route-id="@Model.GameId" class="btn btn-secondary">Back</a>
        </div>
    </div>
    </form>
</div>

SVOAScheduling/Views/Assignment/Modify.cshtml
@model SVOAScheduling.Models.ViewModels.GameViewModel

@{ ViewData["Title"] = "Modify";
    string selectedtxt = ""; }

<h1>Modify Assignment</h1>
@if (ViewBag.Success == true)
{
<div class="col-12 alert alert-success">
    <strong>Assignments </strong>have been removed.
</div>}
@if (ViewBag.Success == false)
{
<div class="col-12 alert alert-warning">
    <strong>Assignments </strong>have<strong> NOT </strong>been removed.
</div>}
<div class="row">
    <div class="col-6">
        <div class="">@Model.Locaton</div>
        <div class="">@Model.HomeTeam vs @Model.VisitingTeam</div>
        <div class="">@Model.GameNumber</div>
        <div class="">@Model.Date.ToString("dd-MMM-yy HH:mm")</div>
    </div>
    <div class="col-6 text-end">
        <a class="btn btn-info" asp-action="Index" asp-controller="Game">Games</a>
    </div>
</div>
<hr />
<form asp-action="Modify">
    <div class="row">
        <div class="col-7 border-left border-right">
             <h5>Assignments</h5>
       <input type="hidden" asp-for="GameId" />
            @for (int i = 0; i < Model.Assignments.Count(); i++)
            {
<div class="row">
    <div class="col-3 text-end">
        <label class="" asp-for="@Model.Assignments[i].AssignmentText">@Model.Assignments[i].AssignmentText</label>:
        <input type="hidden" asp-for="@Model.Assignments[i].AssignmentTypeId" />
        <input type="hidden" asp-for="@Model.Assignments[i].AssignmentId" />
    </div>
    <div class="col-4">
        <select asp-for="@Model.Assignments[i].OfficialId" class="form-control">
            <option value="">Select</option>
            <option value="0">Remove</option>
            @foreach (var item in ViewBag.OfficialId)
            {
                selectedtxt = (Model.Assignments[i].OfficialId == item.Value) ? "selected" : "";

@:  <option value="@item.Value" @selectedtxt>@item.Text</option>
}
        </select>
    </div>
    <div class="col-3">
        <input type="text" placeholder="Gym" asp-for="@Model.Assignments[i].Gym" />
    </div>
</div>}

        </div>
        <div class="col-2">
        <h5>Affiliated Games</h5>
            @for (int j = 0; j < Model.AffiliatedGames.Count(); j++)
            {
<div class="row">
    <div class="col-3">
        <input type="checkbox" class="form-group" asp-for="@Model.AffiliatedGames[j].Checked" />
        <input type="hidden" asp-for="@Model.AffiliatedGames[j].GameId" />
    </div>
    <div class="col-9">@Model.AffiliatedGames[j].Division</div>
</div>
                <div class="row">
                    <div class="col-3 offset-1">
                        <input type="checkbox" class="form-group" asp-for="@Model.AffiliatedGames[j].Reverse" />
                    </div>
                    <div class="col-8">Reverse</div>
                </div>}


        </div>
        <div class="col-2">
            <div class="form-group">
                <div class="">
                    <input type="submit" value="Assign" class="btn btn-primary" />
                </div>
                <div class="pt-2"><a class="btn btn-danger" asp-action="Delete" asp-route-id="@Model.GameId">Clear Assignments</a></div>
            </div>

        </div>
    </div>
</form>


@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

SVOAScheduling/Views/Assignment/_index.cshtml
@model IEnumerable<SVOAScheduling.Models.ViewModels.myScheduleVM>

<div class="row">
    <div class="col-8">
        <h1>My Schedule</h1>
    </div>
    <div class="col-4 text-end">
        <a class="btn btn-primary" asp-controller="Game" asp-action="Index">Full Schedule</a>

    </div>
</div>

<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.MatchDate)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.MatchNumber)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Location)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.HomeTeam)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.VisitingTeam)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.R1)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.R2)
            </th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.MatchDate)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.MatchNumber)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Location)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.HomeTeam)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.VisitingTeam)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.R1)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.R2)
            </td>
        </tr>}
    </tbody>
</table>